spring.application.name=SchoolAppSpring
spring.security.user.name=Pugal
spring.security.user.password=nexusai

spring.datasource.url=jdbc:postgresql://localhost:5432/nexusai
spring.datasource.username=postgres
spring.datasource.password=admin
